# Static build version - changing the version dynamically means you can't
# just click from github to see how things are progressing until the build has
# finished, which could be a bit annoying.
version: 1.{build}-{branch}

image: Visual Studio 2017

environment:
  matrix:
  - platform: Win32
    target: AppVeyor
    visualstudio_string: vs2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

matrix:
  fast_finish: true

init:
# Use CRLF line endings on Windows so users can just use Notepad.
  - git config --global core.autocrlf true

install:
  - git submodule update --init --recursive

build_script:
  - msbuild buildbot.xml /m /t:%target% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - type NUL > bin\portable.ini
  - set folder_name=pcsx2-%APPVEYOR_BUILD_NUMBER%-%visualstudio_string%-%platform%-%target%
  - rename bin %folder_name%
  - 7z a -mx9 %folder_name%.7z %folder_name%

test: off

artifacts:
  - path: $(folder_name).7z
    name: $(visualstudio_string)-$(target)
